//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amortyzacja
    {
        public int NrInwentarzowy { get; set; }
        public System.DateTime DataRozpAmortyzacji { get; set; }
        public decimal WartoscPoczatkowa { get; set; }
        public double StawkaAmortyzacji { get; set; }
        public double WspolczynnikAmortyzacji { get; set; }
        public string MetodaAmortyzacji { get; set; }
        public Nullable<decimal> WartoscBiezaca { get; set; }
    
        public virtual MetodyAmortyzacji MetodyAmortyzacji { get; set; }
        public virtual Sezonowosc Sezonowosc { get; set; }
        public virtual SrodekTrwaly SrodekTrwaly { get; set; }
    }
}
