//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SrodkiTrwaleEntities : DbContext
    {
        public SrodkiTrwaleEntities()
            : base("name=SrodkiTrwaleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amortyzacja> Amortyzacja { get; set; }
        public virtual DbSet<Dokument> Dokument { get; set; }
        public virtual DbSet<Kategoria> Kategoria { get; set; }
        public virtual DbSet<KST> KST { get; set; }
        public virtual DbSet<MetodyAmortyzacji> MetodyAmortyzacji { get; set; }
        public virtual DbSet<Pracownik> Pracownik { get; set; }
        public virtual DbSet<Sezonowosc> Sezonowosc { get; set; }
        public virtual DbSet<SrodekTrwaly> SrodekTrwaly { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
