//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrodekTrwaly
    {
        public string NazwaSrodka { get; set; }
        public int NrInwentarzowy { get; set; }
        public Nullable<int> KST { get; set; }
        public Nullable<int> OsosbaOdp { get; set; }
        public string MiejsceUzytkowania { get; set; }
        public System.DateTime DataZakupu { get; set; }
        public Nullable<System.DateTime> DataLikwidacji { get; set; }
        public string Stan { get; set; }
        public string PrzyczynaZbycia { get; set; }
        public string Kategoria { get; set; }
        public string Dokument { get; set; }
    
        public virtual Amortyzacja Amortyzacja { get; set; }
        public virtual Dokument Dokument1 { get; set; }
        public virtual Kategoria Kategoria1 { get; set; }
        public virtual KST KST1 { get; set; }
        public virtual Pracownik Pracownik { get; set; }
    }
}
